# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

#DATA SCIENCE

# - PANDAS

- Pandas is a Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python.


Key Features
- Data cleaning and preprocessing
- Data filtering and sorting
- Handling missing values
- Data aggregation and grouping
- Merging and joining datasets
- Time-series analysis
- Reading and writing data from multiple formats (CSV, Excel, SQL, JSON, etc.)

#Common Pandas Components
- pandas.Series
- pandas.DataFrame
- pandas.Index



#Frequently Used Submodules
- pandas.io – Input/output operations
- pandas.plotting – Data visualization utilities
- pandas.testing – Testing utilities
- pandas.api – Public API extensions
- pandas.tseries – Time series functionality
- pandas.arrays – Extension array types



#Related Python Packages Commonly Used with Pandas
- NumPy – Numerical computing
- Matplotlib – Data visualization
- Scikit-learn – Machine learning
- SciPy – Scientific computing
- Seaborn – Statistical visualization
- OpenPyXL – Excel file handling
- SQLAlchemy – Database connectivity
"""

#Load library
import pandas as pd

df = pd.DataFrame()

df['names'] = ['John','Rose','Jack']

df['age'] = [15,19,46]

df['country'] = ['Kenya','Uganda','Malawi']

df

#Load library
import pandas as pd

# Create a DataFrame
df = pd.DataFrame(columns=['Name','Age','Country'],
                  data=[
                       ['John',19,'Kenya'],
                       ['Rebecca',16,'Uganda'],
                       ['Lisa',19,'Rwanda'],
                       ['Godfrey',19,'Tanzania'],
                       ['Vivian',19,'Burundi']
                      ])

#show DataFrame
df

df.iloc[0]

type(df)

"""Creating a Series"""

#Load library
import pandas as pd

#Create a Series
series = pd.Series(index=['Name','Age','Country'],data=['John',19,'Uganda'])

#show series
series

type(series)



import pandas as pd
# pyrefly: ignore [missing-import]
import numpy as np

data = {
    'Student_ID': range(1, 51),
    'Name': [f'Student_{i}' for i in range(1, 51)],
    'Age': np.random.randint(18, 30, 50),
    'Gender': np.random.choice(['Male', 'Female'], 50),
    'Course': np.random.choice(
        ['Cybersecurity', 'Data Science', 'Networking', 'Software Engineering'],
        50
    ),
    'GPA': np.round(np.random.uniform(2.0, 4.0, 50), 2),
    'Country': np.random.choice(
        ['Tanzania', 'Kenya', 'Uganda', 'Rwanda'],
        50
    ),
    'Graduated': np.random.choice([True, False], 50)
}

# Create DataFrame
df = pd.DataFrame(data)

# Display first 5 rows
print(df.head())

# Save as CSV
df.to_csv('students.csv', index=False)

# Save as Excel
df.to_excel('students.xlsx', index=False)

# Save as Parquet
df.to_parquet('students.parquet', index=False)

# Save as JSON
df.to_json('students.json', orient='records', indent=4)

print("Files saved successfully!")

# Read CSV
csv_df = pd.read_csv('students.csv')

# Read Excel
excel_df = pd.read_excel('students.xlsx')

# Read Parquet
parquet_df = pd.read_parquet('students.parquet')

# Read JSON
json_df = pd.read_json('students.json')

print(csv_df.head())













"""# combine two dataset"""

import pandas as pd

students = pd.DataFrame({
    'Student_ID': [1, 2, 3, 4, 5],
    'Name': ['John', 'Mary', 'Peter', 'Alice', 'David'],
    'Age': [20, 21, 19, 22, 20],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male']
})

students.to_csv('students.csv', index=False)
print(students)

academic = pd.DataFrame({
    'Student_ID': [1, 2, 3, 4, 5],
    'Course': ['Cybersecurity', 'Networking', 'Data Science', 'Cybersecurity', 'Software Engineering'],
    'GPA': [3.8, 3.5, 3.9, 3.7, 3.6],
    'Year': [2, 3, 1, 4, 2]
})

academic.to_csv('academic_records.csv', index=False)
print(academic)

"""Use merge() when datasets share a common column."""

students = pd.read_csv('students.csv')
academic = pd.read_csv('academic_records.csv')

merged_df = pd.merge(
    students,
    academic,
    on='Student_ID',
    how='inner'
)

print(merged_df)

"""Use concat() when rows correspond in the same order."""

students = pd.read_csv('students.csv')
academic = pd.read_csv('academic_records.csv')

concat_df = pd.concat(
    [students, academic[['Course', 'GPA', 'Year']]],
    axis=1
)

print(concat_df)